const defaultServices={Celular:{'Troca de tela':350,'Troca de bateria':180,'Conector de carga':220,'Atualização de software':120,'Outro reparo':150},Notebook:{'Formatação e Windows':180,'Limpeza interna':140,'Upgrade SSD':120,'Troca de tela':250,'Outro reparo':160},Desktop:{'Formatação e Windows':180,'Limpeza interna':130,'Montagem':250,'Upgrade de hardware':150,'Outro reparo':160}};
function getServices(){
  try{
    const saved=JSON.parse(localStorage.getItem('technocellServices'));
    if(!Array.isArray(saved)||!saved.length)return defaultServices;
    return saved.reduce((acc,item)=>{acc[item.equipment]??={};acc[item.equipment][item.name]=Number(item.price);return acc;},{});
  }catch{return defaultServices;}
}
const services=getServices();
let step=1;const totalSteps=4;const steps=[...document.querySelectorAll('.form-step')];const nextBtn=document.getElementById('nextBtn');const prevBtn=document.getElementById('prevBtn');const serviceSelect=document.getElementById('service');
function selectedEquipment(){return document.querySelector('input[name="equipment"]:checked')?.value||''}function selectedService(){return serviceSelect.value||''}function price(){const e=selectedEquipment(),s=selectedService();return services[e]?.[s]||0}function money(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function fillServices(){const e=selectedEquipment();serviceSelect.innerHTML='<option value="">Selecione</option>';if(e){Object.keys(services[e]||{}).forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;serviceSelect.appendChild(o);});}updateSummary();}
function updateSummary(){document.getElementById('summaryEquipment').textContent=selectedEquipment()||'Não selecionado';document.getElementById('summaryService').textContent=selectedService()||'Não selecionado';document.getElementById('summaryPrice').textContent=money(price());}
function render(){steps.forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));document.getElementById('stepLabel').textContent=`Etapa ${step} de ${totalSteps}`;document.getElementById('progressPercent').textContent=`${step*25}%`;document.getElementById('progressBar').style.width=`${step*25}%`;prevBtn.style.visibility=step===1?'hidden':'visible';nextBtn.style.display=step===4?'none':'inline-flex';if(step===4){document.getElementById('resultEquipment').textContent=selectedEquipment();document.getElementById('resultService').textContent=selectedService();document.getElementById('resultPrice').textContent=money(price());const msg=`Olá! Gostaria de solicitar atendimento na TECHNOCELL R&R.%0A%0AEquipamento: ${selectedEquipment()}%0AMarca: ${document.getElementById('brand').value}%0AModelo: ${document.getElementById('model').value}%0AServiço: ${selectedService()}%0AProblema: ${document.getElementById('problem').value}%0AValor estimado: ${money(price())}%0A%0ANome: ${document.getElementById('name').value}%0ATelefone: ${document.getElementById('phone').value}`;document.getElementById('whatsappResult').href=`https://wa.me/5531973095650?text=${msg}`;}}
function valid(){if(step===1&&!selectedEquipment()){alert('Selecione um equipamento.');return false}if(step===2&&!selectedService()){alert('Selecione o serviço desejado.');return false}if(step===3&&!document.getElementById('name').value.trim()){alert('Informe seu nome.');return false}return true}
document.querySelectorAll('input[name="equipment"]').forEach(i=>i.addEventListener('change',fillServices));serviceSelect.addEventListener('change',updateSummary);nextBtn.addEventListener('click',()=>{if(valid()&&step<totalSteps){step++;render()}});prevBtn.addEventListener('click',()=>{if(step>1){step--;render()}});
const q=new URLSearchParams(location.search).get('tipo');if(q){const map={celular:'Celular',notebook:'Notebook',desktop:'Desktop'};const input=[...document.querySelectorAll('input[name="equipment"]')].find(i=>i.value===map[q]);if(input){input.checked=true;fillServices();}}
render();
